// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIRiQnCS-uGThFLtJZR4xhyGBDmirm_7w',
    appId: '1:793441572452:web:26e856fb4d771827dd7171',
    messagingSenderId: '793441572452',
    projectId: 'rmap-56806',
    authDomain: 'rmap-56806.firebaseapp.com',
    storageBucket: 'rmap-56806.appspot.com',
    measurementId: 'G-VJ5W0FPQ7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1y6ZuEBOsirIgR91G7OSNZUbhDpZzl4s',
    appId: '1:793441572452:android:878fa927c73df64fdd7171',
    messagingSenderId: '793441572452',
    projectId: 'rmap-56806',
    storageBucket: 'rmap-56806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGlzhpjkQ_WM1v944UiEYIfa9JdMv_260',
    appId: '1:793441572452:ios:06890bb2fa93eb07dd7171',
    messagingSenderId: '793441572452',
    projectId: 'rmap-56806',
    storageBucket: 'rmap-56806.appspot.com',
    iosClientId: '793441572452-nlbjp02va6mri0eoc705gm8incvs41am.apps.googleusercontent.com',
    iosBundleId: 'com.example.rMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGlzhpjkQ_WM1v944UiEYIfa9JdMv_260',
    appId: '1:793441572452:ios:06890bb2fa93eb07dd7171',
    messagingSenderId: '793441572452',
    projectId: 'rmap-56806',
    storageBucket: 'rmap-56806.appspot.com',
    iosClientId: '793441572452-nlbjp02va6mri0eoc705gm8incvs41am.apps.googleusercontent.com',
    iosBundleId: 'com.example.rMap',
  );
}
